### ISSUE TITLE
Suggested simplified versions of 2 CAD files from forum

### ISSUE THREAD

**Issue by tareko** [GliaX/Otoscope#16]
Hello @0penBrain and @mwganson.

User `kisolre` on the FreeCAD forums submitted "[a simplified sketch of the specula_holder](https://forum.freecadweb.org/viewtopic.php?f=8&t=38643&p=330601#p330584)" and a "[head lock recreated in PartDesign with proper ellipses](https://forum.freecadweb.org/viewtopic.php?f=8&t=38643&p=330601#p330597)".

Could you guys comment on whether these files supersede yours or what I should do about this?

Thank you

tarek : )

**Comment by mef51** [comment]
I've modified kisolre's `head_lock` model with parabolas instead of ellipses and added a longer tail as part of the assembly changes in PR #19.

I've also updated the main branch with kisolre's simpler sketch in `specula_holder` and simplified the pocket features
